using System;
using System.IO;
using System.Diagnostics;
using System.Windows.Forms;
using System.Drawing;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

namespace SimpleInstaller
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);


            string tempDir = Path.Combine(Path.GetTempPath(), "SimpleInstaller_" + Guid.NewGuid().ToString("N").Substring(0, 8));
            Directory.CreateDirectory(tempDir);

            try
            {

                string simpleExe = Path.Combine(tempDir, "simple.exe");
                ExtractResource("SimpleInstaller.simple.exe", simpleExe);


                string examplesDir = Path.Combine(tempDir, "examples");
                Directory.CreateDirectory(examplesDir);
                ExtractExamples(tempDir);


                string ps1Path = Path.Combine(tempDir, "install.ps1");
                CreateInstallerScript(ps1Path, tempDir);


                Application.Run(new InstallerForm(simpleExe, examplesDir, ps1Path));
            }
            finally
            {

                try { Directory.Delete(tempDir, true); } catch { }
            }
        }

        static void ExtractResource(string resourceName, string outputPath)
        {
            Assembly asm = Assembly.GetExecutingAssembly();
            using (Stream stream = asm.GetManifestResourceStream(resourceName))
            {
                if (stream == null)
                {

                    string[] names = asm.GetManifestResourceNames();
                    foreach (string n in names)
                    {
                        if (n.EndsWith("simple.exe", StringComparison.OrdinalIgnoreCase))
                        {
                            stream = asm.GetManifestResourceStream(n);
                            break;
                        }
                    }
                }

                if (stream != null)
                {
                    using (FileStream fs = new FileStream(outputPath, FileMode.Create))
                    {
                        stream.CopyTo(fs);
                    }
                }
                else
                {
                    throw new Exception($"Resource not found: {resourceName}. Available: {string.Join(", ", asm.GetManifestResourceNames())}");
                }
            }
        }

        static void ExtractExamples(string tempDir)
        {
            Assembly asm = Assembly.GetExecutingAssembly();
            string[] names = asm.GetManifestResourceNames();
            string examplesDir = Path.Combine(tempDir, "examples");

            foreach (string name in names)
            {
                if (name.EndsWith(".spml", StringComparison.OrdinalIgnoreCase) && name.Contains("examples."))
                {
                    string fileName = Path.GetFileName(name);
                    string outputPath = Path.Combine(examplesDir, fileName);
                    using (Stream stream = asm.GetManifestResourceStream(name))
                    using (FileStream fs = new FileStream(outputPath, FileMode.Create))
                    {
                        stream.CopyTo(fs);
                    }
                }
            }
        }

        static void CreateInstallerScript(string ps1Path, string tempDir)
        {
            string script = $@"
# Simple Programming Language Installer
# Auto-generated by SimpleInstaller

$APP_NAME = ""Simple Programming Language""
$VERSION = ""1.5.0""
$PUBLISHER = ""Elijah Shepherd""
$GITHUB_URL = ""https://github.com/elijahshepherd/Simple""
$INSTALL_DIR = Join-Path $env:LOCALAPPDATA ""Simple""
$BIN_DIR = Join-Path $INSTALL_DIR ""bin""
$EXAMPLES_DIR = Join-Path $INSTALL_DIR ""examples""
$EXE_NAME = ""simple.exe""
$UNINSTALL_EXE = ""uninstall.ps1""
$START_MENU_DIR = Join-Path $env:APPDATA ""Microsoft\Windows\Start Menu\Programs\Simple Programming Language""

$SOURCE_EXE = ""{tempDir.Replace("\\", "\\\\")}\simple.exe""
$SOURCE_EXAMPLES = ""{tempDir.Replace("\\", "\\\\")}\examples""

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

function Show-WelcomeScreen {{
    $form = New-Object System.Windows.Forms.Form
    $form.Text = ""$APP_NAME Installer""
    $form.Size = New-Object System.Drawing.Size(500, 380)
    $form.StartPosition = ""CenterScreen""
    $form.FormBorderStyle = ""FixedDialog""
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.BackColor = [System.Drawing.Color]::White

    # Header panel
    $headerPanel = New-Object System.Windows.Forms.Panel
    $headerPanel.Dock = ""Top""
    $headerPanel.Height = 80
    $headerPanel.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)

    $titleLabel = New-Object System.Windows.Forms.Label
    $titleLabel.Text = ""$APP_NAME""
    $titleLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 18, [System.Drawing.FontStyle]::Bold)
    $titleLabel.ForeColor = [System.Drawing.Color]::White
    $titleLabel.AutoSize = $true
    $titleLabel.Location = New-Object System.Drawing.Point(20, 15)

    $subtitleLabel = New-Object System.Windows.Forms.Label
    $subtitleLabel.Text = ""Version $VERSION - Beginner-friendly programming language""
    $subtitleLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 9)
    $subtitleLabel.ForeColor = [System.Drawing.Color]::FromArgb(200, 230, 255)
    $subtitleLabel.AutoSize = $true
    $subtitleLabel.Location = New-Object System.Drawing.Point(20, 50)

    $headerPanel.Controls.Add($titleLabel)
    $headerPanel.Controls.Add($subtitleLabel)
    $form.Controls.Add($headerPanel)

    # Content
    $contentPanel = New-Object System.Windows.Forms.Panel
    $contentPanel.Dock = ""Fill""
    $contentPanel.Padding = New-Object System.Windows.Forms.Padding(20)

    $messageLabel = New-Object System.Windows.Forms.Label
    $messageLabel.Text = ""Welcome to the Simple Programming Language installer!`n`nThis will install Simple v$VERSION to your computer.`n`nClick Install to continue.""
    $messageLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 10)
    $messageLabel.ForeColor = [System.Drawing.Color]::FromArgb(51, 51, 51)
    $messageLabel.AutoSize = $false
    $messageLabel.Size = New-Object System.Drawing.Size(440, 100)
    $messageLabel.Location = New-Object System.Drawing.Point(0, 0)

    $featuresLabel = New-Object System.Windows.Forms.Label
    $featuresLabel.Text = ""What you'll get:""
    $featuresLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 10, [System.Drawing.FontStyle]::Bold)
    $featuresLabel.ForeColor = [System.Drawing.Color]::FromArgb(0, 120, 215)
    $featuresLabel.AutoSize = $true
    $featuresLabel.Location = New-Object System.Drawing.Point(0, 110)

    $featuresList = New-Object System.Windows.Forms.Label
    $featuresList.Text = ""✓  `simple` command available everywhere (added to PATH)`n✓  Run `.spml` files with: simple run file.spml`n✓  Built-in examples: simple run-example hello`n✓  Create new projects: simple new myproject`n✓  Colorful console output, variables, loops, functions`n✓  File I/O, random, time, math, text operations`n✓  Cross-platform: Windows, macOS, Linux""
    $featuresList.Font = New-Object System.Drawing.Font(""Segoe UI"", 9)
    $featuresList.ForeColor = [System.Drawing.Color]::FromArgb(68, 68, 68)
    $featuresList.AutoSize = $false
    $featuresList.Size = New-Object System.Drawing.Size(440, 150)
    $featuresList.Location = New-Object System.Drawing.Point(0, 135)

    $contentPanel.Controls.Add($messageLabel)
    $contentPanel.Controls.Add($featuresLabel)
    $contentPanel.Controls.Add($featuresList)
    $form.Controls.Add($contentPanel)

    # Footer
    $footerPanel = New-Object System.Windows.Forms.Panel
    $footerPanel.Dock = ""Bottom""
    $footerPanel.Height = 60
    $footerPanel.BackColor = [System.Drawing.Color]::FromArgb(240, 240, 240)
    $footerPanel.BorderStyle = ""FixedSingle""

    $installButton = New-Object System.Windows.Forms.Button
    $installButton.Text = ""Install""
    $installButton.Font = New-Object System.Drawing.Font(""Segoe UI"", 10, [System.Drawing.FontStyle]::Bold)
    $installButton.Size = New-Object System.Drawing.Size(100, 35)
    $installButton.Location = New-Object System.Drawing.Point(370, 12)
    $installButton.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)
    $installButton.ForeColor = [System.Drawing.Color]::White
    $installButton.FlatStyle = ""Flat""
    $installButton.FlatAppearance.BorderSize = 0
    $installButton.Cursor = ""Hand""
    $installButton.DialogResult = ""OK""

    $cancelButton = New-Object System.Windows.Forms.Button
    $cancelButton.Text = ""Cancel""
    $cancelButton.Font = New-Object System.Drawing.Font(""Segoe UI"", 10)
    $cancelButton.Size = New-Object System.Drawing.Size(100, 35)
    $cancelButton.Location = New-Object System.Drawing.Point(260, 12)
    $cancelButton.FlatStyle = ""Flat""
    $cancelButton.FlatAppearance.BorderSize = 1
    $cancelButton.Cursor = ""Hand""
    $cancelButton.DialogResult = ""Cancel""

    $footerPanel.Controls.Add($installButton)
    $footerPanel.Controls.Add($cancelButton)
    $form.Controls.Add($footerPanel)

    $form.AcceptButton = $installButton
    $form.CancelButton = $cancelButton

    return $form.ShowDialog() -eq ""OK""
}}

function Show-ProgressScreen {{
    $form = New-Object System.Windows.Forms.Form
    $form.Text = ""$APP_NAME - Installing""
    $form.Size = New-Object System.Drawing.Size(500, 250)
    $form.StartPosition = ""CenterScreen""
    $form.FormBorderStyle = ""FixedDialog""
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.ControlBox = $false
    $form.BackColor = [System.Drawing.Color]::White

    $headerPanel = New-Object System.Windows.Forms.Panel
    $headerPanel.Dock = ""Top""
    $headerPanel.Height = 60
    $headerPanel.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)

    $titleLabel = New-Object System.Windows.Forms.Label
    $titleLabel.Text = ""Installing $APP_NAME""
    $titleLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 16, [System.Drawing.FontStyle]::Bold)
    $titleLabel.ForeColor = [System.Drawing.Color]::White
    $titleLabel.AutoSize = $true
    $titleLabel.Location = New-Object System.Drawing.Point(20, 15)
    $headerPanel.Controls.Add($titleLabel)
    $form.Controls.Add($headerPanel)

    $progressLabel = New-Object System.Windows.Forms.Label
    $progressLabel.Text = ""Preparing...""
    $progressLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 10)
    $progressLabel.ForeColor = [System.Drawing.Color]::FromArgb(51, 51, 51)
    $progressLabel.AutoSize = $false
    $progressLabel.Size = New-Object System.Drawing.Size(440, 30)
    $progressLabel.Location = New-Object System.Drawing.Point(30, 80)
    $form.Controls.Add($progressLabel)

    $progressBar = New-Object System.Windows.Forms.ProgressBar
    $progressBar.Style = ""Marquee""
    $progressBar.MarqueeAnimationSpeed = 30
    $progressBar.Size = New-Object System.Drawing.Size(400, 25)
    $progressBar.Location = New-Object System.Drawing.Point(30, 120)
    $form.Controls.Add($progressBar)

    $detailLabel = New-Object System.Windows.Forms.Label
    $detailLabel.Text = ""Please wait...""
    $detailLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 8)
    $detailLabel.ForeColor = [System.Drawing.Color]::Gray
    $detailLabel.AutoSize = $false
    $detailLabel.Size = New-Object System.Drawing.Size(440, 20)
    $detailLabel.Location = New-Object System.Drawing.Point(30, 155)
    $form.Controls.Add($detailLabel)

    $form.Show()
    $form.Refresh()

    return @{{ Form = $form; Label = $progressLabel; Detail = $detailLabel }}
}}

function Update-ProgressScreen($Screen, $Status, $Detail) {{
    $Screen.Label.Text = $Status
    $Screen.Detail.Text = $Detail
    $Screen.Form.Refresh()
    [System.Windows.Forms.Application]::DoEvents()
}}

function Close-ProgressScreen($Screen) {{
    $Screen.Form.Close()
    $Screen.Form.Dispose()
}}

function Show-FinishScreen {{
    $form = New-Object System.Windows.Forms.Form
    $form.Text = ""$APP_NAME - Installation Complete""
    $form.Size = New-Object System.Drawing.Size(500, 380)
    $form.StartPosition = ""CenterScreen""
    $form.FormBorderStyle = ""FixedDialog""
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.BackColor = [System.Drawing.Color]::White

    $headerPanel = New-Object System.Windows.Forms.Panel
    $headerPanel.Dock = ""Top""
    $headerPanel.Height = 80
    $headerPanel.BackColor = [System.Drawing.Color]::FromArgb(0, 160, 80)

    $titleLabel = New-Object System.Windows.Forms.Label
    $titleLabel.Text = ""✓  Installation Complete!""
    $titleLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 18, [System.Drawing.FontStyle]::Bold)
    $titleLabel.ForeColor = [System.Drawing.Color]::White
    $titleLabel.AutoSize = $true
    $titleLabel.Location = New-Object System.Drawing.Point(20, 20)
    $headerPanel.Controls.Add($titleLabel)
    $form.Controls.Add($headerPanel)

    $contentPanel = New-Object System.Windows.Forms.Panel
    $contentPanel.Dock = ""Fill""
    $contentPanel.Padding = New-Object System.Windows.Forms.Padding(20)

    $messageLabel = New-Object System.Windows.Forms.Label
    $messageLabel.Text = ""$APP_NAME has been successfully installed!`n`nYou can now open a new terminal and run:`n  simple run-example hello`n`nClick Finish to launch Simple and see the welcome message.""
    $messageLabel.Font = New-Object System.Drawing.Font(""Segoe UI"", 10)
    $messageLabel.ForeColor = [System.Drawing.Color]::FromArgb(51, 51, 51)
    $messageLabel.AutoSize = $false
    $messageLabel.Size = New-Object System.Drawing.Size(440, 200)
    $messageLabel.Location = New-Object System.Drawing.Point(0, 0)
    $contentPanel.Controls.Add($messageLabel)
    $form.Controls.Add($contentPanel)

    $footerPanel = New-Object System.Windows.Forms.Panel
    $footerPanel.Dock = ""Bottom""
    $footerPanel.Height = 60
    $footerPanel.BackColor = [System.Drawing.Color]::FromArgb(240, 240, 240)
    $footerPanel.BorderStyle = ""FixedSingle""

    $launchCheck = New-Object System.Windows.Forms.CheckBox
    $launchCheck.Text = ""Launch Simple now""
    $launchCheck.Font = New-Object System.Drawing.Font(""Segoe UI"", 10)
    $launchCheck.ForeColor = [System.Drawing.Color]::FromArgb(51, 51, 51)
    $launchCheck.AutoSize = $true
    $launchCheck.Location = New-Object System.Drawing.Point(20, 15)
    $launchCheck.Checked = $true
    $footerPanel.Controls.Add($launchCheck)

    $finishButton = New-Object System.Windows.Forms.Button
    $finishButton.Text = ""Finish""
    $finishButton.Font = New-Object System.Drawing.Font(""Segoe UI"", 10, [System.Drawing.FontStyle]::Bold)
    $finishButton.Size = New-Object System.Drawing.Size(100, 35)
    $finishButton.Location = New-Object System.Drawing.Point(370, 12)
    $finishButton.BackColor = [System.Drawing.Color]::FromArgb(0, 120, 215)
    $finishButton.ForeColor = [System.Drawing.Color]::White
    $finishButton.FlatStyle = ""Flat""
    $finishButton.FlatAppearance.BorderSize = 0
    $finishButton.Cursor = ""Hand""
    $finishButton.DialogResult = ""OK""
    $footerPanel.Controls.Add($finishButton)

    $form.Controls.Add($footerPanel)
    $form.AcceptButton = $finishButton

    $result = $form.ShowDialog()
    return @{{ Launch = $launchCheck.Checked; Result = $result }}
}}

function Show-ErrorScreen($Message) {{
    [System.Windows.Forms.MessageBox]::Show($Message, ""Installation Error"",
        [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
}}

# Run installation
if (Show-WelcomeScreen) {{
    $progress = Show-ProgressScreen

    try {{
        # Create directories
        Update-ProgressScreen $progress ""Creating directories..."" ""Creating $INSTALL_DIR""
        if (-not (Test-Path $INSTALL_DIR)) {{ New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null }}
        if (-not (Test-Path $BIN_DIR)) {{ New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null }}
        if (-not (Test-Path $EXAMPLES_DIR)) {{ New-Item -ItemType Directory -Path $EXAMPLES_DIR -Force | Out-Null }}
        if (-not (Test-Path $START_MENU_DIR)) {{ New-Item -ItemType Directory -Path $START_MENU_DIR -Force | Out-Null }}

        # Copy executable
        Update-ProgressScreen $progress ""Installing Simple executable..."" ""Copying $EXE_NAME to $BIN_DIR""
        Copy-Item -Path $SOURCE_EXE -Destination (Join-Path $BIN_DIR $EXE_NAME) -Force

        # Copy examples
        Update-ProgressScreen $progress ""Installing examples..."" ""Copying example programs to $EXAMPLES_DIR""
        if (Test-Path $SOURCE_EXAMPLES) {{
            Copy-Item -Path (Join-Path $SOURCE_EXAMPLES ""*.spml"") -Destination $EXAMPLES_DIR -Force
        }}

        # Create uninstaller
        Update-ProgressScreen $progress ""Creating uninstaller..."" ""Writing uninstall script to $INSTALL_DIR""
        $uninstallScript = @\"
<#
.SYNOPSIS
    Uninstaller for Simple Programming Language
#>
`$ErrorActionPreference = ""Stop""
Add-Type -AssemblyName System.Windows.Forms

`$INSTALL_DIR = ""$INSTALL_DIR""
`$BIN_DIR = ""`$INSTALL_DIR\\bin""
`$START_MENU_DIR = ""$START_MENU_DIR""

`$result = [System.Windows.Forms.MessageBox]::Show(
    ""Are you sure you want to uninstall $APP_NAME?"",
    ""Uninstall $APP_NAME"",
    [System.Windows.Forms.MessageBoxButtons]::YesNo,
    [System.Windows.Forms.MessageBoxIcon]::Question
)

if (`$result -ne ""Yes"") {{ exit }}

`$form = New-Object System.Windows.Forms.Form
`$form.Text = ""Uninstalling $APP_NAME""
`$form.Size = New-Object System.Drawing.Size(400, 150)
`$form.StartPosition = ""CenterScreen""
`$form.FormBorderStyle = ""FixedDialog""
`$form.ControlBox = `$false
`$form.BackColor = [System.Drawing.Color]::White

`$label = New-Object System.Windows.Forms.Label
`$label.Text = ""Removing $APP_NAME...""
`$label.Font = New-Object System.Drawing.Font(""Segoe UI"", 10)
`$label.AutoSize = `$true
`$label.Location = New-Object System.Drawing.Point(20, 40)
`$form.Controls.Add(`$label)

`$progressBar = New-Object System.Windows.Forms.ProgressBar
`$progressBar.Style = ""Marquee""
`$progressBar.MarqueeAnimationSpeed = 30
`$progressBar.Size = New-Object System.Drawing.Size(360, 25)
`$progressBar.Location = New-Object System.Drawing.Point(20, 70)
`$form.Controls.Add(`$progressBar)

`$form.Show()
`$form.Refresh()

# Remove from PATH
`$currentPath = [Environment]::GetEnvironmentVariable(""PATH"", ""User"")
if (`$currentPath -like ""*`$BIN_DIR*"") {{
    `$newPath = `$currentPath -replace "";?`$BIN_DIR;?"", "";""
    `$newPath = `$newPath -replace ""^;"", """"
    `$newPath = `$newPath -replace "";$`, """"
    [Environment]::SetEnvironmentVariable(""PATH"", `$newPath, ""User"")
    Add-Type -TypeDefinition @\"
using System;
using System.Runtime.InteropServices;
public class NativeMethods {{
    [DllImport(""user32.dll"", SetLastError = true, CharSet = CharSet.Auto)]
    public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
}}
\"@
    [NativeMethods]::SendMessageTimeout([IntPtr]0xFFFF, 0x001A, [UIntPtr]::Zero, ""Environment"", 0x0002, 5000, [ref]0) | Out-Null
}}

# Remove files and directories
Remove-Item -Path `$INSTALL_DIR -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path `$START_MENU_DIR -Recurse -Force -ErrorAction SilentlyContinue

# Remove registry keys
Remove-Item -Path ""HKCU:\\Software\\Simple"" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path ""HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Simple"" -Recurse -Force -ErrorAction SilentlyContinue

`$form.Close()
`$form.Dispose()

[System.Windows.Forms.MessageBox]::Show(""$APP_NAME has been uninstalled."", ""Uninstall Complete"",
    [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information)
\"@
        Set-Content -Path (Join-Path $INSTALL_DIR $UNINSTALL_EXE) -Value $uninstallScript -Encoding UTF8

        # Add to PATH
        Update-ProgressScreen $progress ""Adding to PATH..."" ""Updating user PATH environment variable""
        $currentPath = [Environment]::GetEnvironmentVariable(""PATH"", ""User"")
        if ($currentPath -notlike ""*$BIN_DIR*"") {{
            $newPath = ""$currentPath;$BIN_DIR""
            [Environment]::SetEnvironmentVariable(""PATH"", $newPath, ""User"")
            Add-Type -TypeDefinition @\"
using System;
using System.Runtime.InteropServices;
public class NativeMethods {{
    [DllImport(""user32.dll"", SetLastError = true, CharSet = CharSet.Auto)]
    public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
}}
\"@
            [NativeMethods]::SendMessageTimeout([IntPtr]0xFFFF, 0x001A, [UIntPtr]::Zero, ""Environment"", 0x0002, 5000, [ref]0) | Out-Null
        }}

        # Create Start Menu shortcuts
        Update-ProgressScreen $progress ""Creating shortcuts..."" ""Adding Start Menu entries""
        $shell = New-Object -ComObject WScript.Shell

        $shortcut = $shell.CreateShortcut(Join-Path $START_MENU_DIR ""Simple.lnk"")
        $shortcut.TargetPath = Join-Path $BIN_DIR $EXE_NAME
        $shortcut.WorkingDirectory = $BIN_DIR
        $shortcut.Description = ""Simple Programming Language""
        $shortcut.Save()

        $shortcut = $shell.CreateShortcut(Join-Path $START_MENU_DIR ""Uninstall.lnk"")
        $shortcut.TargetPath = ""powershell.exe""
        $shortcut.Arguments = ""-ExecutionPolicy Bypass -File `"`$(Join-Path $INSTALL_DIR $UNINSTALL_EXE)`\""""
        $shortcut.WorkingDirectory = $INSTALL_DIR
        $shortcut.Description = ""Uninstall Simple Programming Language""
        $shortcut.Save()

        $shortcut = $shell.CreateShortcut(Join-Path $START_MENU_DIR ""Documentation.lnk"")
        $shortcut.TargetPath = $GITHUB_URL
        $shortcut.Description = ""Simple Programming Language Documentation""
        $shortcut.Save()

        # Write registry for uninstall info
        Update-ProgressScreen $progress ""Registering application..."" ""Writing uninstall registry keys""
        $regPath = ""HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Simple""
        New-Item -Path $regPath -Force | Out-Null
        Set-ItemProperty -Path $regPath -Name ""DisplayName"" -Value $APP_NAME
        Set-ItemProperty -Path $regPath -Name ""DisplayVersion"" -Value $VERSION
        Set-ItemProperty -Path $regPath -Name ""Publisher"" -Value $PUBLISHER
        Set-ItemProperty -Path $regPath -Name ""URLInfoAbout"" -Value $GITHUB_URL
        Set-ItemProperty -Path $regPath -Name ""UninstallString"" -Value ""powershell.exe -ExecutionPolicy Bypass -File `"`$(Join-Path $INSTALL_DIR $UNINSTALL_EXE)`\""""
        Set-ItemProperty -Path $regPath -Name ""NoModify"" -Value 1 -Type DWord
        Set-ItemProperty -Path $regPath -Name ""NoRepair"" -Value 1 -Type DWord

        $ourRegPath = ""HKCU:\\Software\\Simple""
        New-Item -Path $ourRegPath -Force | Out-Null
        Set-ItemProperty -Path $ourRegPath -Name ""InstallDir"" -Value $INSTALL_DIR
        Set-ItemProperty -Path $ourRegPath -Name ""Version"" -Value $VERSION

        Close-ProgressScreen $progress

        $finishResult = Show-FinishScreen
        if ($finishResult.Launch) {{
            Start-Process -FilePath (Join-Path $BIN_DIR $EXE_NAME) -ArgumentList ""run-example hello"" -WorkingDirectory $BIN_DIR -NoNewWindow
        }}
    }}
    catch {{
        Close-ProgressScreen $progress
        Show-ErrorScreen ""Installation failed: `$_`n`n$($_.ScriptStackTrace)""
        exit 1
    }}
}}
"
            File.WriteAllText(ps1Path, script);
        }
    }

    public class InstallerForm : Form
    {
        private string _simpleExe;
        private string _examplesDir;
        private string _ps1Path;
        private Button _btnInstall;
        private Button _btnCancel;
        private Label _lblStatus;
        private ProgressBar _progressBar;
        private CheckBox _chkLaunch;

        public InstallerForm(string simpleExe, string examplesDir, string ps1Path)
        {
            _simpleExe = simpleExe;
            _examplesDir = examplesDir;
            _ps1Path = ps1Path;

            InitializeComponent();
        }

        private void InitializeComponent()
        {
            this.Text = "Simple Programming Language Installer";
            this.Size = new Size(500, 380);
            this.StartPosition = FormStartPosition.CenterScreen;
            this.FormBorderStyle = FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.BackColor = Color.White;


            Panel headerPanel = new Panel();
            headerPanel.Dock = DockStyle.Top;
            headerPanel.Height = 80;
            headerPanel.BackColor = Color.FromArgb(0, 120, 215);

            Label titleLabel = new Label();
            titleLabel.Text = "Simple Programming Language";
            titleLabel.Font = new Font("Segoe UI", 18, FontStyle.Bold);
            titleLabel.ForeColor = Color.White;
            titleLabel.AutoSize = true;
            titleLabel.Location = new Point(20, 15);

            Label subtitleLabel = new Label();
            subtitleLabel.Text = "Version 1.5.0 - Beginner-friendly programming language";
            subtitleLabel.Font = new Font("Segoe UI", 9);
            subtitleLabel.ForeColor = Color.FromArgb(200, 230, 255);
            subtitleLabel.AutoSize = true;
            subtitleLabel.Location = new Point(20, 50);

            headerPanel.Controls.Add(titleLabel);
            headerPanel.Controls.Add(subtitleLabel);
            this.Controls.Add(headerPanel);


            Panel contentPanel = new Panel();
            contentPanel.Dock = DockStyle.Fill;
            contentPanel.Padding = new Padding(20);

            Label messageLabel = new Label();
            messageLabel.Text = "Welcome to the Simple Programming Language installer!\n\nThis will install Simple v1.5.0 to your computer.\n\nClick Install to continue.";
            messageLabel.Font = new Font("Segoe UI", 10);
            messageLabel.ForeColor = Color.FromArgb(51, 51, 51);
            messageLabel.AutoSize = false;
            messageLabel.Size = new Size(440, 100);
            messageLabel.Location = new Point(0, 0);

            Label featuresLabel = new Label();
            featuresLabel.Text = "What you'll get:";
            featuresLabel.Font = new Font("Segoe UI", 10, FontStyle.Bold);
            featuresLabel.ForeColor = Color.FromArgb(0, 120, 215);
            featuresLabel.AutoSize = true;
            featuresLabel.Location = new Point(0, 110);

            Label featuresList = new Label();
            featuresList.Text = "✓  `simple` command available everywhere (added to PATH)\n✓  Run `.spml` files with: simple run file.spml\n✓  Built-in examples: simple run-example hello\n✓  Create new projects: simple new myproject\n✓  Colorful console output, variables, loops, functions\n✓  File I/O, random, time, math, text operations\n✓  Cross-platform: Windows, macOS, Linux";
            featuresList.Font = new Font("Segoe UI", 9);
            featuresList.ForeColor = Color.FromArgb(68, 68, 68);
            featuresList.AutoSize = false;
            featuresList.Size = new Size(440, 150);
            featuresList.Location = new Point(0, 135);

            contentPanel.Controls.Add(messageLabel);
            contentPanel.Controls.Add(featuresLabel);
            contentPanel.Controls.Add(featuresList);
            this.Controls.Add(contentPanel);


            Panel footerPanel = new Panel();
            footerPanel.Dock = DockStyle.Bottom;
            footerPanel.Height = 60;
            footerPanel.BackColor = Color.FromArgb(240, 240, 240);
            footerPanel.BorderStyle = BorderStyle.FixedSingle;

            _btnInstall = new Button();
            _btnInstall.Text = "Install";
            _btnInstall.Font = new Font("Segoe UI", 10, FontStyle.Bold);
            _btnInstall.Size = new Size(100, 35);
            _btnInstall.Location = new Point(370, 12);
            _btnInstall.BackColor = Color.FromArgb(0, 120, 215);
            _btnInstall.ForeColor = Color.White;
            _btnInstall.FlatStyle = FlatStyle.Flat;
            _btnInstall.FlatAppearance.BorderSize = 0;
            _btnInstall.Cursor = Cursors.Hand;
            _btnInstall.Click += BtnInstall_Click;

            _btnCancel = new Button();
            _btnCancel.Text = "Cancel";
            _btnCancel.Font = new Font("Segoe UI", 10);
            _btnCancel.Size = new Size(100, 35);
            _btnCancel.Location = new Point(260, 12);
            _btnCancel.FlatStyle = FlatStyle.Flat;
            _btnCancel.FlatAppearance.BorderSize = 1;
            _btnCancel.Cursor = Cursors.Hand;
            _btnCancel.Click += (s, e) => this.Close();

            footerPanel.Controls.Add(_btnInstall);
            footerPanel.Controls.Add(_btnCancel);
            this.Controls.Add(footerPanel);

            this.AcceptButton = _btnInstall;
        }

        private async void BtnInstall_Click(object sender, EventArgs e)
        {
            _btnInstall.Enabled = false;
            _btnCancel.Enabled = false;


            this.Controls.Clear();
            ShowProgressView();

            try
            {
                await RunInstallation();


                this.Controls.Clear();
                ShowFinishView();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Installation failed: {ex.Message}", "Error",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                this.Close();
            }
        }

        private void ShowProgressView()
        {
            Panel headerPanel = new Panel();
            headerPanel.Dock = DockStyle.Top;
            headerPanel.Height = 60;
            headerPanel.BackColor = Color.FromArgb(0, 120, 215);

            Label titleLabel = new Label();
            titleLabel.Text = "Installing Simple Programming Language";
            titleLabel.Font = new Font("Segoe UI", 16, FontStyle.Bold);
            titleLabel.ForeColor = Color.White;
            titleLabel.AutoSize = true;
            titleLabel.Location = new Point(20, 15);
            headerPanel.Controls.Add(titleLabel);
            this.Controls.Add(headerPanel);

            _lblStatus = new Label();
            _lblStatus.Text = "Preparing...";
            _lblStatus.Font = new Font("Segoe UI", 10);
            _lblStatus.ForeColor = Color.FromArgb(51, 51, 51);
            _lblStatus.AutoSize = false;
            _lblStatus.Size = new Size(440, 30);
            _lblStatus.Location = new Point(30, 80);
            this.Controls.Add(_lblStatus);

            _progressBar = new ProgressBar();
            _progressBar.Style = ProgressBarStyle.Marquee;
            _progressBar.MarqueeAnimationSpeed = 30;
            _progressBar.Size = new Size(400, 25);
            _progressBar.Location = new Point(30, 120);
            this.Controls.Add(_progressBar);

            Label detailLabel = new Label();
            detailLabel.Text = "Please wait...";
            detailLabel.Font = new Font("Segoe UI", 8);
            detailLabel.ForeColor = Color.Gray;
            detailLabel.AutoSize = false;
            detailLabel.Size = new Size(440, 20);
            detailLabel.Location = new Point(30, 155);
            this.Controls.Add(detailLabel);
        }

        private void UpdateProgress(string status, string detail)
        {
            if (_lblStatus != null) _lblStatus.Text = status;
            if (_progressBar != null) _progressBar.Refresh();
            Application.DoEvents();
        }

        private async Task RunInstallation()
        {
            UpdateProgress("Creating directories...", $"Creating {Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Simple")}");
            await Task.Delay(100);

            string installDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Simple");
            string binDir = Path.Combine(installDir, "bin");
            string examplesDir = Path.Combine(installDir, "examples");
            string startMenuDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                @"Microsoft\Windows\Start Menu\Programs\Simple Programming Language");

            Directory.CreateDirectory(installDir);
            Directory.CreateDirectory(binDir);
            Directory.CreateDirectory(examplesDir);
            Directory.CreateDirectory(startMenuDir);

            UpdateProgress("Installing Simple executable...", $"Copying simple.exe to {binDir}");
            File.Copy(_simpleExe, Path.Combine(binDir, "simple.exe"), true);
            await Task.Delay(100);

            UpdateProgress("Installing examples...", $"Copying example programs to {examplesDir}");
            if (Directory.Exists(_examplesDir))
            {
                foreach (string file in Directory.GetFiles(_examplesDir, "*.spml"))
                {
                    File.Copy(file, Path.Combine(examplesDir, Path.GetFileName(file)), true);
                }
            }
            await Task.Delay(100);

            UpdateProgress("Creating uninstaller...", "Writing uninstall script");
            string uninstallScript = CreateUninstallScript(installDir, binDir, startMenuDir);
            File.WriteAllText(Path.Combine(installDir, "uninstall.ps1"), uninstallScript);
            await Task.Delay(100);

            UpdateProgress("Adding to PATH...", "Updating user PATH environment variable");
            AddToUserPath(binDir);
            await Task.Delay(100);

            UpdateProgress("Creating shortcuts...", "Adding Start Menu entries");
            CreateShortcuts(binDir, installDir, startMenuDir);
            await Task.Delay(100);

            UpdateProgress("Registering application...", "Writing uninstall registry keys");
            WriteRegistryKeys(installDir);
        }

        private string CreateUninstallScript(string installDir, string binDir, string startMenuDir)
        {
            return $@"
# Uninstaller for Simple Programming Language
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms

$INSTALL_DIR = '{installDir.Replace("\\", "\\\\")}'
$BIN_DIR = '{binDir.Replace("\\", "\\\\")}'
$START_MENU_DIR = '{startMenuDir.Replace("\\", "\\\\")}'

$result = [System.Windows.Forms.MessageBox]::Show(
    'Are you sure you want to uninstall Simple Programming Language?',
    'Uninstall Simple Programming Language',
    [System.Windows.Forms.MessageBoxButtons]::YesNo,
    [System.Windows.Forms.MessageBoxIcon]::Question
)

if ($result -ne 'Yes') {{ exit }}

$form = New-Object System.Windows.Forms.Form
$form.Text = 'Uninstalling Simple Programming Language'
$form.Size = New-Object System.Drawing.Size(400, 150)
$form.StartPosition = 'CenterScreen'
$form.FormBorderStyle = 'FixedDialog'
$form.ControlBox = $false
$form.BackColor = [System.Drawing.Color]::White

$label = New-Object System.Windows.Forms.Label
$label.Text = 'Removing Simple Programming Language...'
$label.Font = New-Object System.Drawing.Font('Segoe UI', 10)
$label.AutoSize = $true
$label.Location = New-Object System.Drawing.Point(20, 40)
$form.Controls.Add($label)

$progressBar = New-Object System.Windows.Forms.ProgressBar
$progressBar.Style = 'Marquee'
$progressBar.MarqueeAnimationSpeed = 30
$progressBar.Size = New-Object System.Drawing.Size(360, 25)
$progressBar.Location = New-Object System.Drawing.Point(20, 70)
$form.Controls.Add($progressBar)

$form.Show()
$form.Refresh()

# Remove from PATH
$currentPath = [Environment]::GetEnvironmentVariable('PATH', 'User')
if ($currentPath -like '*$BIN_DIR*') {{
    $newPath = $currentPath -replace ';?$BIN_DIR;?', ';'
    $newPath = $newPath -replace '^;', ''
    $newPath = $newPath -replace ';$', ''
    [Environment]::SetEnvironmentVariable('PATH', $newPath, 'User')
    Add-Type -TypeDefinition @\"
using System;
using System.Runtime.InteropServices;
public class NativeMethods {{
    [DllImport('user32.dll', SetLastError = true, CharSet = CharSet.Auto)]
    public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
}}
\"@
    [NativeMethods]::SendMessageTimeout([IntPtr]0xFFFF, 0x001A, [UIntPtr]::Zero, 'Environment', 0x0002, 5000, [ref]0) | Out-Null
}}

# Remove files and directories
Remove-Item -Path $INSTALL_DIR -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path $START_MENU_DIR -Recurse -Force -ErrorAction SilentlyContinue

# Remove registry keys
Remove-Item -Path 'HKCU:\\Software\\Simple' -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Simple' -Recurse -Force -ErrorAction SilentlyContinue

$form.Close()
$form.Dispose()

[System.Windows.Forms.MessageBox]::Show('Simple Programming Language has been uninstalled.', 'Uninstall Complete',
    [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information)
";
        }

        private void AddToUserPath(string binDir)
        {
            string currentPath = Environment.GetEnvironmentVariable("PATH", EnvironmentVariableTarget.User);
            if (!currentPath.Contains(binDir))
            {
                string newPath = currentPath + ";" + binDir;
                Environment.SetEnvironmentVariable("PATH", newPath, EnvironmentVariableTarget.User);


                NativeMethods.SendMessageTimeout(
                    (IntPtr)0xFFFF, 0x001A, UIntPtr.Zero, "Environment",
                    0x0002, 5000, out UIntPtr _);
            }
        }

        private void CreateShortcuts(string binDir, string installDir, string startMenuDir)
        {
            Type shellType = Type.GetTypeFromProgID("WScript.Shell");
            dynamic shell = Activator.CreateInstance(shellType);


            dynamic shortcut = shell.CreateShortcut(Path.Combine(startMenuDir, "Simple.lnk"));
            shortcut.TargetPath = Path.Combine(binDir, "simple.exe");
            shortcut.WorkingDirectory = binDir;
            shortcut.Description = "Simple Programming Language";
            shortcut.Save();


            shortcut = shell.CreateShortcut(Path.Combine(startMenuDir, "Uninstall.lnk"));
            shortcut.TargetPath = "powershell.exe";
            shortcut.Arguments = $"-ExecutionPolicy Bypass -File \"{Path.Combine(installDir, "uninstall.ps1")}\"";
            shortcut.WorkingDirectory = installDir;
            shortcut.Description = "Uninstall Simple Programming Language";
            shortcut.Save();


            shortcut = shell.CreateShortcut(Path.Combine(startMenuDir, "Documentation.lnk"));
            shortcut.TargetPath = "https://github.com/elijahshepherd/Simple";
            shortcut.Description = "Simple Programming Language Documentation";
            shortcut.Save();
        }

        private void WriteRegistryKeys(string installDir)
        {
            string regPath = @"Software\Microsoft\Windows\CurrentVersion\Uninstall\Simple";
            using (var key = Microsoft.Win32.Registry.CurrentUser.CreateSubKey(regPath))
            {
                key.SetValue("DisplayName", "Simple Programming Language");
                key.SetValue("DisplayVersion", "1.5.0");
                key.SetValue("Publisher", "Elijah Shepherd");
                key.SetValue("URLInfoAbout", "https://github.com/elijahshepherd/Simple");
                key.SetValue("UninstallString", $"powershell.exe -ExecutionPolicy Bypass -File \"{Path.Combine(installDir, "uninstall.ps1")}\"");
                key.SetValue("NoModify", 1, Microsoft.Win32.RegistryValueKind.DWord);
                key.SetValue("NoRepair", 1, Microsoft.Win32.RegistryValueKind.DWord);
            }

            string ourRegPath = @"Software\Simple";
            using (var key = Microsoft.Win32.Registry.CurrentUser.CreateSubKey(ourRegPath))
            {
                key.SetValue("InstallDir", installDir);
                key.SetValue("Version", "1.5.0");
            }
        }

        private void ShowFinishView()
        {
            Panel headerPanel = new Panel();
            headerPanel.Dock = DockStyle.Top;
            headerPanel.Height = 80;
            headerPanel.BackColor = Color.FromArgb(0, 160, 80);

            Label titleLabel = new Label();
            titleLabel.Text = "✓  Installation Complete!";
            titleLabel.Font = new Font("Segoe UI", 18, FontStyle.Bold);
            titleLabel.ForeColor = Color.White;
            titleLabel.AutoSize = true;
            titleLabel.Location = new Point(20, 20);
            headerPanel.Controls.Add(titleLabel);
            this.Controls.Add(headerPanel);

            Panel contentPanel = new Panel();
            contentPanel.Dock = DockStyle.Fill;
            contentPanel.Padding = new Padding(20);

            Label messageLabel = new Label();
            messageLabel.Text = "Simple Programming Language has been successfully installed!\n\nYou can now open a new terminal and run:\n  simple run-example hello\n\nClick Finish to launch Simple and see the welcome message.";
            messageLabel.Font = new Font("Segoe UI", 10);
            messageLabel.ForeColor = Color.FromArgb(51, 51, 51);
            messageLabel.AutoSize = false;
            messageLabel.Size = new Size(440, 200);
            messageLabel.Location = new Point(0, 0);
            contentPanel.Controls.Add(messageLabel);
            this.Controls.Add(contentPanel);

            Panel footerPanel = new Panel();
            footerPanel.Dock = DockStyle.Bottom;
            footerPanel.Height = 60;
            footerPanel.BackColor = Color.FromArgb(240, 240, 240);
            footerPanel.BorderStyle = BorderStyle.FixedSingle;

            _chkLaunch = new CheckBox();
            _chkLaunch.Text = "Launch Simple now";
            _chkLaunch.Font = new Font("Segoe UI", 10);
            _chkLaunch.ForeColor = Color.FromArgb(51, 51, 51);
            _chkLaunch.AutoSize = true;
            _chkLaunch.Location = new Point(20, 15);
            _chkLaunch.Checked = true;
            footerPanel.Controls.Add(_chkLaunch);

            Button finishButton = new Button();
            finishButton.Text = "Finish";
            finishButton.Font = new Font("Segoe UI", 10, FontStyle.Bold);
            finishButton.Size = new Size(100, 35);
            finishButton.Location = new Point(370, 12);
            finishButton.BackColor = Color.FromArgb(0, 120, 215);
            finishButton.ForeColor = Color.White;
            finishButton.FlatStyle = FlatStyle.Flat;
            finishButton.FlatAppearance.BorderSize = 0;
            finishButton.Cursor = Cursors.Hand;
            finishButton.Click += (s, e) => {
                if (_chkLaunch.Checked)
                {
                    string binDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Simple", "bin");
                    Process.Start(new ProcessStartInfo
                    {
                        FileName = Path.Combine(binDir, "simple.exe"),
                        Arguments = "run-example hello",
                        WorkingDirectory = binDir,
                        UseShellExecute = true
                    });
                }
                this.Close();
            };
            footerPanel.Controls.Add(finishButton);

            this.Controls.Add(footerPanel);
            this.AcceptButton = finishButton;
        }
    }

    internal static class NativeMethods
    {
        [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
        public static extern IntPtr SendMessageTimeout(IntPtr hWnd, uint Msg, UIntPtr wParam, string lParam, uint fuFlags, uint uTimeout, out UIntPtr lpdwResult);
    }
}